// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using superhero_api.Data;

#nullable disable

namespace superhero_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240720140432_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("superhero_api.Models.Superhero", b =>
                {
                    b.Property<int>("SuperheroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("superhero_id");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("SuperheroName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("superhero_name");

                    b.HasKey("SuperheroId");

                    b.ToTable("Superheros");
                });
#pragma warning restore 612, 618
        }
    }
}
